


out: main.cpp conf.cpp Engine.cpp
	g++ -o out -std=c++11 -I/usr/local/include/SDL2 -I/usr/local/include -L/usr/local/lib main.cpp conf.cpp Engine.cpp -lSDL2main -lSDL2 -lSDL2_image -lpng


clean: 
	rm -rf out